### ISSUE TITLE
previous-value

### ISSUE THREAD

**Issue by lishine** [ecomfe/react-hooks#3]
These are just my two cents
I have issues with the naming.
For example - use previous value - but actually it mutates the value. So are the other functions.
useOriginalDeepCopy actually does regular copy

**Comment by otakustay** [comment]
`usePreviousValue` returns a previous version of current value but not mutate it

```js
const previous = usePreviousValue(current);
```

Neither `previous` nor `current` is mutated in this hook, `current` and `previous` can be different objects, we don't force to make them having same content.

`useOriginalDeepCopy` doesn't mutate value neither, there is a story behind the naming of `useOriginalCopy`.

When we discovered the functionality of `useOriginalCopy` is a great help in react ecosystem, we describe the prop change of react component as "having a copy of a photo every day", we may get a photo **exactly the same as the original one** but it is not the original photo, and react requires the original one instead of the "exact content but not exact reference" one. This hook is to help developer retrieve back the very original photo from a copied photo to satisfy react's equals algorithm, so it is named `useOriginalCopy`.

**Comment by lishine** [comment]
Yep. Actually hard to judge without having the need and knowing the use case.
